manipulator_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - jnt1_rev
    - jnt2_rev
    - jnt3_rev
    - jnt4_rev
    - jnt5_rev
    - jnt6_rev
  gains:
    jnt1_rev:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jnt2_rev:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jnt3_rev:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jnt4_rev:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jnt5_rev:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    jnt6_rev:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
